const assert = require('node:assert/strict');
const M = require('./engine.js');
const UI = require('./app.js');
let raw = JSON.stringify({...M.defaults(),day:12,prices:{...M.defaults().prices,kimchi:41000}});
const storage = {getItem:()=>raw,setItem:(key,value)=>{assert.equal(key,'mi-cay-planner-v1');raw=value;}};
const old = UI.restore(storage);
assert.equal(old.state.day,12);assert.equal(old.state.prices.kimchi,41000);
UI.persist(storage,old.state,false);
const valid = raw;
assert.throws(()=>UI.persist(storage,{...old.state,day:NaN},false));assert.equal(raw,valid);
raw='{broken';const damaged=UI.restore(storage);assert.equal(damaged.raw,raw);assert(damaged.error);
assert.throws(()=>UI.persist(storage,M.defaults(),true));assert.equal(raw,'{broken');
assert.throws(()=>UI.persist({setItem(){throw Error('quota');}},M.defaults(),false),/quota/);
assert(UI.restore({getItem(){throw Error('denied');}}).error);
console.log('PASS: restore bản cũ, giá, bản hỏng, bảo vệ bản hợp lệ, lỗi storage.');
assert(UI.numberError('',1,10,1));assert(UI.numberError('0',1,10,1));
assert(UI.numberError('1.5',1,10,1));assert.equal(UI.numberError('0',0,30,1),'');
assert(UI.numberError('500',1000,105000,1000));assert(UI.numberError('35500',1000,105000,1000));
assert.equal(UI.numberError('.45',.05,10,.05),'');
assert.equal(UI.searchText('PHÔ MAI ĐỎ'),'pho mai do');
assert(UI.menuMatch(M.byId.kimchi,M.defaults(),'available','kim'));
assert(!UI.menuMatch(M.byId.tomyum,M.defaults(),'available',''));
assert(UI.menuMatch(M.byId.tomyum,M.defaults(),'all',''));
assert(!UI.menuMatch(M.byId.bo,M.defaults(),'selling','pho mai'));
const comparison=(profit,base,se=1)=>({stats:{profit,se},baseline:{profit:base,se}});
assert.equal(UI.decision(comparison(200,100),M.defaults()).kind,'gain');
assert.equal(UI.decision(comparison(100,200),M.defaults()).kind,'keep');
assert.equal(UI.decision(comparison(100,99,100),M.defaults()).kind,'uncertain');
assert.equal(UI.decision(comparison(100,200),{...M.defaults(),prices:{...M.defaults().prices,kimchi:70000}}).kind,'constraint');
