const assert = require('node:assert/strict');
const M = require('./engine.js');
const UI = require('./app.js');
let raw = JSON.stringify({...M.defaults(),day:12,prices:{...M.defaults().prices,kimchi:41000}});
const storage = {getItem:()=>raw,setItem:(key,value)=>{assert.equal(key,'mi-cay-planner-v1');raw=value;}};
const old = UI.restore(storage);
assert.equal(old.state.day,12);assert.equal(old.state.prices.kimchi,41000);
UI.persist(storage,old.state);
const valid = raw;
assert.throws(()=>UI.persist(storage,{...old.state,day:NaN}));assert.equal(raw,valid);
raw='{broken';const damaged=UI.restore(storage);assert.deepEqual(damaged.state,M.defaults());assert(damaged.error);
UI.persist(storage,damaged.state);assert.equal(UI.restore(storage).error,'');
assert.throws(()=>UI.persist({setItem(){throw Error('quota');}},M.defaults()),/quota/);
assert(UI.restore({getItem(){throw Error('denied');}}).error);
console.log('PASS: restore bản cũ, giá, bản hỏng, bảo vệ bản hợp lệ, lỗi storage.');
assert(UI.numberError('',1,10,1));assert(UI.numberError('0',1,10,1));
assert(UI.numberError('1.5',1,10,1));assert.equal(UI.numberError('0',0,30,1),'');
assert(UI.numberError('500',1000,105000,1000));assert(UI.numberError('35500',1000,105000,1000));
assert.equal(UI.numberError('.45',.05,10,.05),'');
assert.equal(UI.searchText('PHÔ MAI ĐỎ'),'pho mai do');
assert(UI.menuMatch(M.byId.kimchi,M.defaults(),'available','kim'));
assert(!UI.menuMatch(M.byId.tomyum,M.defaults(),'available',''));
assert(UI.menuMatch(M.byId.tomyum,M.defaults(),'all',''));
assert(!UI.menuMatch(M.byId.bo,M.defaults(),'selling','pho mai'));
const comparison=(profit,base,se=1)=>({stats:{profit,se},baseline:{profit:base,se}});
assert.equal(UI.decision(comparison(200,100),M.defaults()).kind,'gain');
assert.equal(UI.decision(comparison(100,200),M.defaults()).kind,'keep');
assert.equal(UI.decision(comparison(100,99,100),M.defaults()).kind,'uncertain');
assert.equal(UI.decision(comparison(100,200),{...M.defaults(),prices:{...M.defaults().prices,kimchi:70000}}).kind,'constraint');
assert.throws(()=>UI.persist(storage,{...M.defaults(),prices:{...M.defaults().prices,tomyum:NaN}}));
console.log('PASS: rỗng/step/range, search/lọc và nhánh khuyến nghị tăng/giảm/nhiễu/an toàn.');

const legacy={...M.defaults(),level:9};delete legacy.chapter;raw=JSON.stringify(legacy);
assert.equal(UI.restore(storage).state.chapter,4);assert(UI.restore(storage).migrated);
raw=JSON.stringify({...legacy,chapter:1});assert.equal(UI.restore(storage).state.chapter,1);
UI.persist(storage,UI.restore(storage).state);assert.equal(UI.restore(storage).state.chapter,1);
raw=JSON.stringify({...legacy,level:1,chapter:3});assert(UI.restore(storage).error);
console.log('PASS: migrate cấu hình thiếu chương, giữ chương thấp khi level cao, lưu lại chương, chặn chương vượt cấp.');

const secretState={...M.defaults(),day:3,secret:{day:3,broth:'kimchi',status:'active'}};
UI.persist(storage,secretState);assert.deepEqual(UI.restore(storage).state.secret,{day:3,broth:null,status:'none'});
raw=JSON.stringify({...secretState,day:4});assert.deepEqual(UI.restore(storage).state.secret,{day:4,broth:null,status:'none'});
const reduced={...secretState,level:1,secret:{day:3,broth:'tomyum',status:'active'}};
assert.deepEqual(UI.normalizeSecret(reduced),{day:3,broth:null,status:'none'});
assert.throws(()=>UI.persist({setItem(){throw Error('quota');}},secretState),/quota/);
console.log('PASS: bỏ secret cũ khi nhớ/restore, đổi ngày, giảm cấp/mất nồi, save lỗi không làm sai state.');
