const assert=require('node:assert/strict');
const M=require('./engine.js');
const s=M.defaults();
assert(Math.abs(M.traffic(s,s.prices,0,4)-1.2*1.015*.75)<1e-10);
const low={...s.prices,kimchi:1000}, floor={...s.prices,kimchi:29000};
assert.equal(M.traffic(s,low,0,4),M.traffic(s,floor,0,4));
assert.equal(M.traffic(s,{...s.prices,bo:45000},0,4),M.traffic(s,s.prices,0,4));
assert.equal(M.expensive('bo',22500,s),false);
assert.equal(M.expensive('bo',23000,s),true);
assert.equal(M.expensive('kimchi',60000,s),false);
assert.equal(M.expensive('kimchi',61000,s),true);
const busy={...s,day:30,stars:5,level:9,broths:M.broths.map(x=>x.id),tops:M.tops.map(x=>x.id),upgrades:['sign','tiktok','kol','gmap','flyer','speaker','seat4','app'],action:2,extra:10};
const slow=M.batch(busy,busy.prices,40,33);
const fast=M.batch({...busy,action:.1,extra:0},busy.prices,40,33);
assert(slow.timeout>0); assert(slow.full>0); assert(fast.served>slow.served);
assert(Math.abs(slow.profit-(slow.sales-slow.fee-slow.cost+slow.tips-slow.fixed-slow.waste))<1e-7);
assert.deepEqual(M.simulate(s,s.prices,41),M.simulate(s,s.prices,41));
assert.throws(()=>M.validate({...s,broths:[]}),/nước lèo/);
console.log('PASS: thu hút, ngưỡng giá, tái lập seed, quá tải, công suất, sổ lợi nhuận, cấu hình.');
